### ISSUE TITLE
Upgrade Keycloak

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-user-server#7]
Upgrade Keycloak to the current version as needed.

See https://github.com/metadatacenter/cedar-user-server/issues/2.

**Comment by graybeal** [comment]
See also https://github.com/metadatacenter/cedar-parent/pull/22
See also https://github.com/metadatacenter/cedar-project/issues/1131
See also https://github.com/metadatacenter/cedar-project/issues/904

**Comment by martinjoconnor** [comment]
Managed to upgrade from 11.02 to 15.02 on my local machine using guide at: https://www.keycloak.org//docs/latest/upgrading/index.html

No need to incrementally go through releases, at least for 11.02 to 15.02 upgrade.

Important additional tip is to copy `mysql-connector-java-5.1.49.jar` to the `modules/system/layers/base/com/mysql/jdbc/main/` directory of the new Keycloak directory and also `module.xml` to that location (otherwise this JAR is not found at startup and Keycloak cannot connect to the MySQL database).

Here is a suitable `module.xml`:

```
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.0" name="com.mysql.jdbc">
   <resources>
      <resource-root path="mysql-connector-java-5.1.49.jar"/>
   </resources>
   <dependencies>
      <module name="javax.api"/>
      <module name="javax.transaction.api"/>
   </dependencies>
</module>
```
